version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 8081:8080
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB}